---
- targets:
    - "localhost:7979|http://h3123:token@192.168.1.2:9000/api/system/metrics/org.graylog2.journal.entries-uncommitted|graylog"
  labels:
    env: "prod"
    project: "evo"
    owner: "profiteroles"
    severity: "normal"

  
