---
- targets:
    - "bbe-certprod-dbank-common.apps.ocp.bank.rrr.vip-clients|proxied_http_2xx|https://ips-api.bank.ru/|prod.ips-api.bank.ru"
  labels:
    env: "prod"
    project: "evo"
    owner: "profiteroles"
    severity: "high"

  
