---
- targets:
    - "bbe-certprod-dbank-common.apps.ocp.bank.rrr.vip-clients|http_2xx|https://mbr-log.bank.rrr.vip-clients/|cert.mbr-log.bank.rrr.vip-clients"
  labels:
    env: "cert"
    project: "evo"
    owner: "profiteroles"
    severity: "high"

  
