---
- targets:
    #- "bbe-certprod-dbank-common.apps.ocp.bank.rrr.vip-clients|proxied_http_2xx|https://evo.bank.ru/|prod.evo.bank.ru"
    - "blackbox_exporter.localhost|proxied_http_2xx|https://evo.bank.ru/|prod.evo.bank.ru"
  labels:
    env: "prod"
    project: "evo"
    owner: "profiteroles"
    severity: "high"

  
