---
- targets:
    - "blackbox_exporter.localhost|http_2xx|http://192.168.1.2:9000/api/system/lbstatus|prod.graylog.ilb.status"
  labels:
    env: "prod"
    project: "evo"
    owner: "profiteroles"
    severity: "high"

  
